CREATE DATABASE IF NOT EXISTS iaffirm;

USE iaffirm;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    first_name VARCHAR(70) NOT NULL,
    last_name VARCHAR(70) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(15) DEFAULT NULL,
    img_url VARCHAR(225) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- CREATE TABLE users (
--     id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
--     first_name VARCHAR(30) DEFAULT NULL,
--     last_name VARCHAR(30) DEFAULT NULL,
--     email VARCHAR(70) DEFAULT NULL,
--     password VARCHAR(255) DEFAULT NOT NULL,
--     phone VARCHAR(15) DEFAULT NULL,
--     img_url VARCHAR(225) DEFAULT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY (id),
--     CONSTRAINT UQ_Users_Email UNIQUE (email)
-- ); 

